// here are the accessCodes generated by using bcryptjs.hashSync('code') ie bcryptjs.hashSync('the mandalorian')
const accessGrantedList = [
  '$2a$10$RJNlrbVZ9KumAp0z1CVP/OsD/OweAsoUA50C.Ws7DjDQalH3Tjz4K',
  '$2a$10$AtshmUR.lEK6FAkTFDSrHefGSxPtKrhvP/18ft4Fv6OsWKP3rSKs2',
  '$2a$10$9QGmoNht7RBY4C8fl3I6heNKrSf4DH9IpU.iRBtLXOia9nFJMHsvC',
  '$2a$10$2mTVe4nDp4t5kQSZlJjqMeQoLTMyfxeniDIx6rDFeBevw4xLTxS9u',
  '$2a$10$IK8L0pUE0o7vpdJmcF9G1ehXHRAJ2ke4DZ7jxUc.Tl2v2vn1XuDnq',
  '$2a$10$SjGuEXNzqfYwkwkynz5TrODJXTlvGto7BRvZ4mILIz2M.o/xKbH52',
];

module.exports = { accessGrantedList };
